lesson_17_Logs_Analyzer_easy
eugene-okulik/denisofflive pull request #16
Opened 2024-03-21 10:04 UTC by denisofflive

2024-03-21 15:10 UTC, eugene-okulik requested changes
А как же это:

> Также, программа должна вывести кусок строки, где был найден текст: 5 слов до найденного слова, найденное слово, 5 слов после найденного слова.

:-(

2024-03-22 11:12 UTC, denisofflive commented
> А как же это:
> 
> > Также, программа должна вывести кусок строки, где был найден текст: 5 слов до найденного слова, найденное слово, 5 слов после найденного слова.
> 
> :-(



> А как же это:
> 
> > Также, программа должна вывести кусок строки, где был найден текст: 5 слов до найденного слова, найденное слово, 5 слов после найденного слова.
> 
> :-(

Поифксил, сделал немного по-другому

2024-03-22 15:17 UTC, eugene-okulik requested changes
Зачем же ты всё поломал?!

2024-03-22 15:17 UTC, eugene-okulik commented on homework/denis_denisov/lesson_17_Logs_Analyzer_easy/Logs_Analyzer_easy.py
> +path = r'D:\denisofflive\homework\eugene_okulik\data\logs'
У меня на компе нет такого пути. Да и по заданию путь к файлам нужно было ждать от пользователя при запуске программы, но ты почему-то этот код удалил.

2024-03-22 15:17 UTC, eugene-okulik commented on homework/denis_denisov/lesson_17_Logs_Analyzer_easy/Logs_Analyzer_easy.py
> +text = "Sql exception for geometry"
Текст для поиска тоже должен указать пользователь при запуске

2024-03-22 15:17 UTC, eugene-okulik commented on homework/denis_denisov/lesson_17_Logs_Analyzer_easy/Logs_Analyzer_easy.py
> +                    end = min(line.index(text_to_find) + len(text_to_find) + 5, len(line))
Сейчас ты распечатываешь 5 символов до слова и 5 символов после. А нужно 5 **слов** до и 5 **слов** после.

2024-03-23 08:11 UTC, denisofflive commented
> Зачем же ты всё поломал?!

откатился обратно, добавил 5 слов до и 5 слов после.

2024-03-23 10:43 UTC, eugene-okulik requested changes
Хорошей практикой написания кода является его запуск )))  
Если починить эти args, то всё работает хорошо.

2024-03-23 10:43 UTC, eugene-okulik commented on homework/denis_denisov/lesson_17_Logs_Analyzer_easy/Logs_Analyzer_easy.py
> +                print(f"Файл: {file}, в строке {i}: {context}")
У тебя в args есть args.path_folder и args.text, но в коде ты обращаешься к args.path и args.value. В итоге программа сыпет ошибками.

2024-03-23 11:41 UTC, denisofflive commented on homework/denis_denisov/lesson_17_Logs_Analyzer_easy/Logs_Analyzer_easy.py
> +                print(f"Файл: {file}, в строке {i}: {context}")
> У тебя в args есть args.path_folder и args.text, но в коде ты обращаешься к args.path и args.value. В итоге программа сыпет ошибками.

пофиксил args)))

2024-03-23 16:52 UTC, eugene-okulik approved these changes

2024-03-23 16:52 UTC, merged